// DragCSS — CSS Applier
// Applies CSS property changes to matched file locations

const vscode = require('vscode');
const path = require('path');

class CSSApplier {
  /**
   * Apply a CSS change to a matched file location.
   * @param {vscode.Uri} uri — File URI
   * @param {vscode.Range} range — Range of the matched CSS rule block
   * @param {{selector: string, diffs: Object}} change — The change to apply
   * @returns {Promise<boolean>}
   */
  async applyChange(uri, range, change) {
    const doc = await vscode.workspace.openTextDocument(uri);
    const ruleText = doc.getText(range);

    // Parse existing properties in the rule
    const braceStart = ruleText.indexOf('{');
    const braceEnd = ruleText.lastIndexOf('}');
    if (braceStart === -1 || braceEnd === -1) return false;

    const header = ruleText.substring(0, braceStart + 1);
    let body = ruleText.substring(braceStart + 1, braceEnd);
    const footer = ruleText.substring(braceEnd);

    // Detect indentation from existing properties
    const indentMatch = body.match(/\n(\s+)\S/);
    const indent = indentMatch ? indentMatch[1] : '  ';

    // Apply each property change
    for (const [prop, val] of Object.entries(change.diffs)) {
      const afterValue = val.after;
      // Check if property already exists in the rule
      const propRegex = new RegExp(
        '(' + prop.replace(/-/g, '\\-') + ')\\s*:\\s*([^;]+);?',
        'g'
      );

      if (propRegex.test(body)) {
        // Replace existing value
        body = body.replace(propRegex, `$1: ${afterValue};`);
      } else {
        // Add new property before the closing brace
        body += `${indent}${prop}: ${afterValue};\n`;
      }
    }

    const newRuleText = header + body + footer;

    // Apply the edit
    const edit = new vscode.WorkspaceEdit();
    edit.replace(uri, range, newRuleText);
    const success = await vscode.workspace.applyEdit(edit);

    if (success) {
      // Show the modified file
      await vscode.window.showTextDocument(doc, {
        selection: range,
        preview: false
      });
    }

    return success;
  }

  /**
   * Create a new CSS override file with all pending changes.
   * @param {Array<{selector: string, diffs: Object}>} changes
   */
  async createOverrideFile(changes) {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders || workspaceFolders.length === 0) {
      vscode.window.showErrorMessage('DragCSS: No workspace folder open.');
      return;
    }

    const rootUri = workspaceFolders[0].uri;
    const fileUri = vscode.Uri.joinPath(rootUri, 'dragcss-overrides.css');

    let content = '/* Generated by DragCSS — Visual CSS Changes */\n';
    content += '/* Review and integrate these into your stylesheets */\n\n';

    for (const change of changes) {
      content += `${change.selector} {\n`;
      for (const [prop, val] of Object.entries(change.diffs)) {
        content += `  ${prop}: ${val.after};\n`;
      }
      content += '}\n\n';
    }

    const encoder = new TextEncoder();
    await vscode.workspace.fs.writeFile(fileUri, encoder.encode(content));
    const doc = await vscode.workspace.openTextDocument(fileUri);
    await vscode.window.showTextDocument(doc);

    vscode.window.showInformationMessage(
      'DragCSS: Created dragcss-overrides.css — review and integrate into your stylesheets.'
    );
  }
}

module.exports = { CSSApplier };
